---
name: CustomJoin
version: 1.6.0
main: SixpennyYard\CustomJoin\CustomJoin
api: 4.2.0
src-namespace-prefix: SixpennyYard\CustomJoin

permissions:
  customjoin.wc:
    default: op
    description: send a welcome message
...
